version: "3.3"

services:
  converter:
    depends_on:
      - virtuoso
      - postgres
    links:
        - virtuoso
        - postgres
    build:
      context: .
      dockerfile: Dockerfile
    image: ltmartin/motivo_to_rdf_converter:latest
    restart: on-failure
    stdin_open: true
    tty: true
    volumes:
      - ./data:/converter/data

  virtuoso:
    image: openlink/virtuoso-opensource-7:latest
    restart: always
    volumes:
    - virtuoso-database:/database
    ports:
    - "8890:8890"

  postgres:
    image: postgres:14.2-alpine
    command: postgres -c 'max_connections=200'
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: converter
    volumes:
      - postgres-database:/var/lib/postgresql/data

volumes:
 postgres-database:
   external: true
 virtuoso-database:
   external: true